baseURL = "https://lehre.bpkleer.de/spss101/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[params]
  title = "WBT: Einstieg in SPSS leicht gemacht"
  theme = "hugo-theme-learn"
  themesdir = "./themes/"
  metaDataFormat = "yaml"
  defaultContentLanguageInSubdir = false
  themeVariant = "jlug"
  description = "Einstieg in SPSS leicht gemacht"
  author = "B. Philipp Kleer"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = ">"
  disableInlineCopyToClipBoard = true
  languageCode = "de-DE"
  defaultContentLanguage = "de"
  [assets]
    disableHLJS = true
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
  name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 1"
  url = "https://lehre.bpkleer.de/spss101/lb1/"
  weight = 10

[[menu.shortcuts]]
  name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 2"
  url = "https://lehre.bpkleer.de/spss101/lb2/"
  weight = 20

[[menu.shortcuts]]
  name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 3"
  url = "https://lehre.bpkleer.de/spss101/lb3/"
  weight = 30

[[menu.shortcuts]]
  name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 4"
  url = "https://lehre.bpkleer.de/spss101/lb4/"
  weight = 40

[[menu.shortcuts]]
  name = "<i class='fas fa-bullhorn'></i> Credits"
  url = "/credits"
  weight = 60

[[menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "/tags"
  weight = 70

[[menu.shortcuts]]
  name = "<i class='fab fa-gitlab'></i> Gitlab Repo"
  url = "https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-spss/"
  weight = 80

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

